
const Collection = [
    {
id:1,
name:"Modelling Agency",
image: "img1.jpeg",
alt:"valueofalt",
link:"./MainHome/Modelling_Agency",
discription:"Modelling Agency",
},
{
    id:2,
    name:"Fashion Show",
    image:"2.jpg",
    alt:"valueofalt",
    link:"./MainHome/FashionShow",
    discription:"Fashion Show",
    },
{
    id:3,
    name:"Dance Industry",
    image:"img2.jpeg",
    alt:"valueofalt",
    link:"./MainHome/DanceShow",
    discription:"Dance Industry",
    },
    {
        id:4,
        name:"Music Industry",
        image:"img3.jpeg",
        alt:"valueofalt",
        link:"./MainHome/MusicShow",
        discription:"Music Industry",
        },
        {
            id:5,
            name:"Fashion Store",
            image:"img4.jpeg",
            alt:"valueofalt",
            link:"./MainHome/FashionStore_Vendors",
            discription:"Fashion Store",
            },
            {
                id:6,
                name:"Fullscreen Showcase",
                image:"img5.jpeg",
                alt:"valueofalt",
                link:"./MainHome/FullscreenShowcase",
                discription:"Fullscreen Showcase",
                },
                {
                    id:7,
                    name:"Portfolio Magazine",
                    image:"img6.jpeg",
                    alt:"valueofalt",
                    link:"./MainHome/PortfolioMagazine",
                    discription:"Portfolio Magazine",
                    },
                    {
                        id:8,
                        name:"Makeup artist & hair stylist",
                        image: "img1.jpeg",
                        alt:"valueofalt",
                        link:"./MainHome/Makeup_Hair_Vendors",
                        discription:"Makeup artist & hair stylist",
                        },
                        {
                            id:9,
                            name:"Our Team",
                            image:"img2.jpeg",
                            alt:"valueofalt",
                            link:"./MainHome/Shoot_Team",
                            discription:"Our Team",
                            },
                            {
                                id:10,
                                name:"Fashion Designer",
                                image:"img3.jpeg",
                                alt:"valueofalt",
                                link:"./MainHome/FashionDesiner",
                                discription:"Fashion Designer",
                                },
                                // {
                                //     id:11,
                                //     name:"Jwellery Shop",
                                //     image:"img4.jpeg",
                                //     alt:"valueofalt",
                                //     link:"./MainHome/JwelleryShop",
                                //     discription:"ritesh yadav",
                                //     },
                                    {
                                        id:12,
                                        name:"",
                                        image:"img5.jpeg",
                                        alt:"valueofalt",
                                        link:"./MainHome/Portfolios",
                                        discription:"Portfolios",
                                        },
                                        
];


export default Collection;