const services = [

    {   id: 1,
        name: "Edudome",
        category : "education",
        description:"Online learning platform",
    },
    {   id: 2,
        name: "Public Speaking",
        category : "education",
        description:"Digital library",
    },
    {   id: 3,
        name: "Start-Up",
        category : "education",
        description:"Skill-building workshops",
    },
    {   id: 4,
        name: "Orientation",
        category : "education",
        description:"Exam preparation platform",
    },
    {   id: 5,
        name: "Counseling",
        category : "education",
        description:"E-learning resources",
    },
    {   id: 6,
        name: "Dance Industry",
        category : "entertainment",
        description:"description",
    },
    {   id: 7,
        name: "Fashion Show",
        category : "entertainment",
        description:"Gaming platform",
    },
    {   id: 8,
        name: "Modeling Workshop",
        category : "entertainment",
        description:"Streaming service",
    },
    {   id: 9,
        name: "Starface Production",
        category : "entertainment",
        description:"Music streaming service",
    },
    {   id: 10,
        name: "Acting Course",
        category : "entertainment",
        description:"Film review community",
    },
    {   id: 11,
        name: "Dealing with legal Aspects",
        category : "IT Sector",
        description:"Arcade gaming center",
    },
    {   id: 12,
        name: "Advertisement",
        category : "IT Sector",
        description:"IT consultancy services",
    },
    {   id: 13,
        name: "Social Media Handling",
        category : "IT Sector",
        description:"Software development company",
    },
    {   id: 14,
        name: "Designing Website",
        category : "IT Sector",
        description:"Cybersecurity solutions",
    },
    {   id: 15,
        name: "MAnagement",
        category : "IT Sector",
        description:"Data analytics services",
    },
    
]

export default services;
